{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.enjoydambience",
    "module": "kotlinbard",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "veodaxekyzczth3z7izcna3vte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinbard-0.0.1.jar",
          "url": "kotlinbard-0.0.1.jar",
          "size": 163718,
          "sha512": "d299082bcf91508167b9aac7173056b35217eef5063ee090a2e817301b636591cbeade9c58b190988725fa29b0528868c8d597cfa8ae691073c0fb92e363b5b8",
          "sha256": "985f4357dade6738eec87c6d495db78eafa44ad6e46ee68c3a3d74ade7fde8ae",
          "sha1": "f77e7719b2e4acd259897d3b4c3bb8c92001d7d5",
          "md5": "279e41b8b389d966f30c44f8169f16cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinbard-0.0.1.jar",
          "url": "kotlinbard-0.0.1.jar",
          "size": 163718,
          "sha512": "d299082bcf91508167b9aac7173056b35217eef5063ee090a2e817301b636591cbeade9c58b190988725fa29b0528868c8d597cfa8ae691073c0fb92e363b5b8",
          "sha256": "985f4357dade6738eec87c6d495db78eafa44ad6e46ee68c3a3d74ade7fde8ae",
          "sha1": "f77e7719b2e4acd259897d3b4c3bb8c92001d7d5",
          "md5": "279e41b8b389d966f30c44f8169f16cd"
        }
      ]
    }
  ]
}
