{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.enjoydambience",
    "module": "kotlinbard",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "bzskqtvi2ndm3eknfuly7klnou"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinbard-0.0.1.jar",
          "url": "kotlinbard-0.0.1.jar",
          "size": 163718,
          "sha512": "9f307ac115b4741e05d272a935ce1beb1f268d7c9d265fda264a154bceb9a4ff1acea5999c7983da09a7e0c22c67bc7cbcc81a60e0313ef81301777389e54b08",
          "sha256": "840fba52695a2f411784aacd854a042cf448f7f6f682782a7ecae7e0c55d0fcd",
          "sha1": "56e926d489f2cae70624db9531acc0bd0a2fee80",
          "md5": "2c91513284ea0bcc3e787840eef4edce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinbard-0.0.1.jar",
          "url": "kotlinbard-0.0.1.jar",
          "size": 163718,
          "sha512": "9f307ac115b4741e05d272a935ce1beb1f268d7c9d265fda264a154bceb9a4ff1acea5999c7983da09a7e0c22c67bc7cbcc81a60e0313ef81301777389e54b08",
          "sha256": "840fba52695a2f411784aacd854a042cf448f7f6f682782a7ecae7e0c55d0fcd",
          "sha1": "56e926d489f2cae70624db9531acc0bd0a2fee80",
          "md5": "2c91513284ea0bcc3e787840eef4edce"
        }
      ]
    }
  ]
}
